# Generated by Django 5.0.6 on 2024-08-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinformation',
            name='college_name',
        ),
    ]
