# Generated by Django 5.0.6 on 2024-07-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='email',
            new_name='college_email',
        ),
        migrations.AddField(
            model_name='collegerequest',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
