# Generated by Django 5.0.6 on 2024-08-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel_allotment',
            name='prefered_room_type',
            field=models.CharField(blank=True, choices=[('not-applied', 'Not-applied'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=125, null=True, verbose_name='Prefered Room'),
        ),
    ]
