# Generated by Django 5.0.6 on 2024-08-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='branch_name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='branch_name'),
        ),
    ]
