# Generated by Django 5.0.6 on 2024-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloned_departments_for_no_dues',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=225, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='departments_for_no_dues',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=225, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='no_dues_list',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=225, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='overall_no_dues_request',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('not_applied', 'Not Applied')], default='not_applied', max_length=225, verbose_name='Status'),
        ),
    ]
