# Generated by Django 5.0.6 on 2024-08-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_registration_number_per_college',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('registration_number', 'college')},
        ),
    ]
