# Generated by Django 5.0.6 on 2024-06-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonafide',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='bonafide',
            name='course_start_date',
        ),
        migrations.RemoveField(
            model_name='bonafide',
            name='department',
        ),
        migrations.RemoveField(
            model_name='bonafide',
            name='year_semester',
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='batch',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='batch'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='course_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='course start date'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='department',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='year_semester',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='year/semester'),
        ),
        migrations.AddField(
            model_name='bonafide',
            name='fee_structure',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='fee_structure'),
        ),
        migrations.AddField(
            model_name='bonafide',
            name='status',
            field=models.CharField(choices=[('not-applied', 'Not-applied'), ('applied', 'Applied'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default=('not-applied', 'Not-applied'), max_length=225, verbose_name='status'),
        ),
    ]
