# Generated by Django 5.0.6 on 2024-08-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_academicinformation_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('office', 'Office'), ('faculty', 'Faculty'), ('super-admin', 'Super-Admin'), ('principal', 'Principal'), ('caretaker', 'Caretaker'), ('department', 'Department'), ('registrar', 'Registrar')], max_length=20),
        ),
    ]
