# Generated by Django 5.0.6 on 2024-06-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_bonafide_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonafide',
            name='supporting_document',
            field=models.BinaryField(blank=True, null=True, verbose_name='supporting_document'),
        ),
    ]
