# Generated by Django 5.0.6 on 2024-06-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mess_fee_payment_total_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mess_fee_payment',
            old_name='Total_fees',
            new_name='total_fees',
        ),
        migrations.RemoveField(
            model_name='mess_fee_payment',
            name='fees',
        ),
        migrations.AddField(
            model_name='mess_fee_payment',
            name='maintainance_fees',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='maintainance-fee'),
        ),
        migrations.AddField(
            model_name='mess_fee_payment',
            name='mess_fees',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='mess-fee'),
        ),
        migrations.AddField(
            model_name='mess_fee_payment',
            name='security_fees',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='security-fee'),
        ),
    ]
