# Generated by Django 5.0.6 on 2024-08-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hostel_allotment_prefered_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelrooms',
            name='current_occupancy',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='current occupancy'),
        ),
    ]
