# Generated by Django 5.0.6 on 2024-07-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_email_college_college_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('office', 'Office'), ('faculty', 'Faculty'), ('super-admin', 'Super-Admin'), ('principal', 'Principal'), ('caretaker', 'Caretaker'), ('department', 'Department')], max_length=20),
        ),
    ]
