# Generated by Django 5.0.6 on 2024-06-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinformation',
            name='branch',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='branch'),
        ),
    ]
