# Generated by Django 5.0.6 on 2024-06-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_total_fees_mess_fee_payment_total_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess_fee_payment',
            name='registration_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hostel_room_allotment'),
        ),
    ]
