# Generated by Django 5.0.6 on 2024-08-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester_registration',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_registrations_college', to='api.college'),
        ),
    ]
