# Generated by Django 5.0.6 on 2024-06-02 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bonafide_supporting_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafide',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_no', to=settings.AUTH_USER_MODEL),
        ),
    ]
