# Generated by Django 5.0.6 on 2024-08-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hostelrooms_current_occupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_allotment',
            name='prefered_room_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=125, null=True, verbose_name='Prefered Room'),
        ),
    ]
