# Generated by Django 5.0.6 on 2024-06-17 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_mess_fee_payment_registration_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='No_Dues_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(max_length=225, verbose_name='Department')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='waiting for approval', max_length=225, verbose_name='status')),
                ('approved_date', models.DateField(verbose_name='approved_date')),
                ('applied_date', models.DateField(verbose_name='applied_date')),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
            ],
        ),
        migrations.CreateModel(
            name='Overall_No_Dues_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True, verbose_name='name')),
                ('branch', models.CharField(blank=True, max_length=225, null=True, verbose_name='branch')),
                ('father_name', models.CharField(blank=True, max_length=225, null=True, verbose_name='father_name')),
                ('category', models.CharField(blank=True, max_length=225, null=True, verbose_name='category')),
                ('self_declaration', models.BooleanField(default=False, verbose_name='self_declaration')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('pending', 'Pending'), ('approved', 'Approved')], default='not applied', max_length=225, verbose_name='status')),
                ('registration_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
