# Generated by Django 5.0.6 on 2024-06-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_academicinformation_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinformation',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='year'),
        ),
    ]
