# Generated by Django 5.0.6 on 2024-08-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_semester_registration_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifysemesterregistration',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_verification', to='api.college'),
        ),
    ]
