# Generated by Django 5.0.6 on 2024-08-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafide',
            name='status',
            field=models.CharField(choices=[('not-applied', 'Not-applied'), ('applied', 'Applied'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not-applied', max_length=225, verbose_name='status'),
        ),
    ]
