# Generated by Django 5.0.6 on 2024-08-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegerequest',
            name='college_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='college code'),
        ),
    ]
