# Generated by Django 5.0.6 on 2024-07-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_academicinformation_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mess_fee_payment',
            name='maintainance_fees',
        ),
        migrations.RemoveField(
            model_name='mess_fee_payment',
            name='mess_fees',
        ),
        migrations.RemoveField(
            model_name='mess_fee_payment',
            name='security_fees',
        ),
        migrations.AddField(
            model_name='mess_fee_payment',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('mees fee', 'Mees Fee'), ('maintainance fee', 'Maintainance Fees'), ('security fee', 'Security Fee')], max_length=225, null=True, verbose_name='fee_type'),
        ),
    ]
