# Generated by Django 5.0.6 on 2024-06-17 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_no_dues_list_overall_no_dues_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overall_no_dues_request',
            name='registration_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Overall_No_due', to=settings.AUTH_USER_MODEL),
        ),
    ]
