# Generated by Django 5.0.6 on 2024-06-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subject_bonafide_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instructor'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=225, verbose_name='semester_name')),
                ('subjects', models.ManyToManyField(related_name='semester_subjects', to='api.subject', verbose_name='subjects')),
            ],
        ),
    ]
