# Generated by Django 5.0.6 on 2024-08-20 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mess_fee_payment_unique_mess_fee_per_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel_no_due_request',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.college'),
        ),
        migrations.AlterField(
            model_name='hostel_no_due_request',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='approved_date'),
        ),
        migrations.AlterField(
            model_name='hostel_no_due_request',
            name='status',
            field=models.CharField(choices=[('not-applied', 'Not-applied'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not-applied', max_length=225),
        ),
    ]
