# Generated by Django 5.0.6 on 2024-08-16 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_verifysemesterregistration_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel_allotment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.college'),
        ),
        migrations.AlterField(
            model_name='hostel_allotment',
            name='status',
            field=models.CharField(blank=True, choices=[('not-applied', 'Not-applied'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not-applied', max_length=225, null=True),
        ),
    ]
