# Generated by Django 5.0.6 on 2024-07-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_mess_fee_payment_maintainance_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess_fee_payment',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('mees_fee', 'Mees_Fee'), ('maintainance_fee', 'Maintainance Fees'), ('security_fee', 'Security Fee')], max_length=225, null=True, verbose_name='fee_type'),
        ),
    ]
