# Generated by Django 5.0.6 on 2024-06-17 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_overall_no_dues_request_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overall_no_dues_request',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='overall_no_dues_request',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overall_no_dues_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
