# Generated by Django 5.0.6 on 2024-08-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hostel_no_due_request_college_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel_no_due_request',
            old_name='Maintance_fees_date',
            new_name='maintance_fees_date',
        ),
        migrations.RenameField(
            model_name='hostel_no_due_request',
            old_name='Mess_fees_date',
            new_name='mess_fees_date',
        ),
    ]
