# Generated by Django 5.0.6 on 2024-06-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_subject_instructor_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='branch',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='branch'),
        ),
    ]
