# Generated by Django 5.0.6 on 2024-08-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bonafide_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafide',
            name='status',
            field=models.CharField(choices=[('not-applied', 'Not-applied'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not-applied', max_length=225, verbose_name='status'),
        ),
    ]
