# Generated by Django 5.0.6 on 2024-07-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_mess_fee_payment_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_registration',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=225, null=True),
        ),
    ]
