# Generated by Django 5.0.6 on 2024-06-17 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_overall_no_dues_request_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overall_no_dues_request',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='overall_no_dues_request',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overall_no_due', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='overall_no_dues_request',
            name='branch',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='overall_no_dues_request',
            name='category',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='overall_no_dues_request',
            name='father_name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='overall_no_dues_request',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='overall_no_dues_request',
            name='self_declaration',
            field=models.BooleanField(default=False, verbose_name='Self Declaration'),
        ),
        migrations.AlterField(
            model_name='overall_no_dues_request',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('pending', 'Pending'), ('approved', 'Approved'), ('not_applied', 'Not Applied')], default='not_applied', max_length=225, verbose_name='Status'),
        ),
    ]
