# Generated by Django 5.0.6 on 2024-06-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_subject_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='subject_id'),
        ),
    ]
