# Generated by Django 5.0.6 on 2024-07-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_semester_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifysemesterregistration',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='remarks'),
        ),
    ]
