# Generated by Django 5.0.6 on 2024-06-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_subject_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(blank=True, null=True, verbose_name='semester_registration_date')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_registrations', to='api.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_registration_student', to='api.personalinformation')),
            ],
        ),
    ]
