# Generated by Django 5.0.6 on 2024-08-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_complaint_college_guest_room_request_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(blank=True, choices=[('registered', 'Registered'), ('under investigation', 'Under Investigation'), ('resolved', 'Resolved')], default='registered', max_length=225, null=True, verbose_name='status'),
        ),
    ]
