# Generated by Django 5.0.6 on 2024-06-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_overall_no_dues_request_registration_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='registration_number',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='guest_room_request',
            old_name='registration_number',
            new_name='user',
        ),
    ]
