# Generated by Django 5.0.6 on 2024-06-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_semester_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_registration_student', to='api.userprofile'),
        ),
    ]
