# Generated by Django 5.0.6 on 2024-08-23 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments_for_no_dues',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.college'),
        ),
    ]
