# Generated by Django 5.0.6 on 2024-08-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_academicinformation_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Branch_name',
            new_name='branch_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('office', 'Office'), ('faculty', 'Faculty'), ('super-admin', 'Super-Admin'), ('hod', 'HOD'), ('principal', 'Principal'), ('caretaker', 'Caretaker'), ('department', 'Department'), ('registrar', 'Registrar')], max_length=20),
        ),
    ]
