# Generated by Django 5.0.6 on 2024-06-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_registration_number_complaint_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel_no_due_request',
            old_name='registration_number',
            new_name='user',
        ),
    ]
