# Generated by Django 5.0.6 on 2024-07-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_verifysemesterregistration_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('office', 'Office'), ('faculty', 'Faculty'), ('admin', 'Admin'), ('principal', 'Principal'), ('caretaker', 'Caretaker'), ('department', 'Department')], max_length=10),
        ),
    ]
