# Generated by Django 5.0.6 on 2024-06-17 12:26

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_registration_number_hostel_no_due_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='no_dues_list',
            name='request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, related_name='no_dues_list', to='api.overall_no_dues_request'),
        ),
        migrations.AlterField(
            model_name='no_dues_list',
            name='applied_date',
            field=models.DateField(auto_now=True, verbose_name='applied_date'),
        ),
        migrations.AlterField(
            model_name='no_dues_list',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='approved_date'),
        ),
    ]
