# Generated by Django 5.0.6 on 2024-06-08 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_semester_registration_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True, verbose_name='name')),
                ('branch', models.CharField(blank=True, max_length=225, null=True, verbose_name='branch')),
                ('complaint_type', models.CharField(blank=True, choices=[('ragging related', 'Ragging Related'), ('academic fees', 'Academic Fees'), ('classes related', 'Classes Related'), ('others', 'Others')], max_length=225, null=True, verbose_name='complaint type')),
                ('complaint_description', models.TextField(blank=True, null=True, verbose_name='complaint description')),
                ('status', models.CharField(blank=True, choices=[('not-applied', 'Not-applied'), ('applied', 'Applied'), ('pending', 'Pending'), ('approved', 'Approved')], max_length=225, null=True, verbose_name='status')),
                ('registration_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_number_or_employee_no', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_room_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_request', models.CharField(choices=[('for staying parents', 'For Staying Parents'), ('for staying relatives', 'For Staying Relatives'), ('for staying invited delegate', 'For Staying Invited Delegate'), ('for staying alumni', 'For Staying Alumni')], max_length=225)),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='from_date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='to_date')),
                ('no_of_persons', models.IntegerField(blank=True, null=True, verbose_name='no_of_persons')),
                ('registration_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_room_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_marksheet', models.BinaryField(blank=True, null=True, verbose_name='marksheet')),
                ('status', models.CharField(blank=True, choices=[('not-applied', 'Not-applied'), ('applied', 'Applied'), ('pending', 'Pending'), ('approved', 'Approved')], default='not-applied', max_length=225, null=True)),
                ('registration_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allotment_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_No_Due_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=225, null=True, verbose_name='semester')),
                ('Maintance_fees_date', models.DateField(blank=True, null=True, verbose_name='Maintance_fees')),
                ('Mess_fees_date', models.DateField(blank=True, null=True, verbose_name='Mess_fees')),
                ('self_declaration', models.BooleanField(blank=True, default=False, null=True, verbose_name='self_agree')),
                ('requested_date', models.DateField(blank=True, null=True, verbose_name='requested_date')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='approves_date')),
                ('registration_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Hostel_no_due_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_Room_Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_room', models.CharField(blank=True, max_length=225, null=True, verbose_name='hostel_room')),
                ('registration_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_room_allotment', to='api.hostel_allotment')),
            ],
        ),
    ]
