# Generated by Django 5.0.6 on 2024-08-23 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_departments_for_no_dues_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='no_dues_list',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.college'),
        ),
    ]
