# Generated by Django 5.0.6 on 2024-06-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_no_dues_list_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments_for_no_due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(max_length=225, verbose_name='Department')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='waiting for approval', max_length=225, verbose_name='status')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='approved_date')),
                ('applied_date', models.DateField(auto_now=True, verbose_name='applied_date')),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
            ],
        ),
        migrations.RemoveField(
            model_name='no_dues_list',
            name='Department_name',
        ),
        migrations.RemoveField(
            model_name='no_dues_list',
            name='status',
        ),
        migrations.AddField(
            model_name='no_dues_list',
            name='departments',
            field=models.ManyToManyField(related_name='no_due_lists', to='api.departments_for_no_due'),
        ),
    ]
