# Generated by Django 5.0.6 on 2024-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_departments_for_no_dues_college_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('college', 'subject_code'), name='unique_college_subject_code'),
        ),
    ]
