# Generated by Django 5.0.6 on 2024-06-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_departments_for_no_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel_allotment',
            name='cgpa',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='CGPA'),
        ),
        migrations.AddField(
            model_name='no_dues_list',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='waiting for approval', max_length=225, verbose_name='status'),
        ),
    ]
