# Generated by Django 5.0.6 on 2024-06-20 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_hostel_allotment_cgpa_no_dues_list_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_number_or_employee_no', to=settings.AUTH_USER_MODEL),
        ),
    ]
