# Generated by Django 5.0.6 on 2024-06-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_registration_number_hostel_allotment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel_room_allotment',
            old_name='registration_number',
            new_name='user',
        ),
    ]
