# Generated by Django 5.0.6 on 2024-06-20 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest_room_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_room_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
