# Generated by Django 5.0.6 on 2024-06-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_registration_number_hostel_room_allotment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel_room_allotment',
            old_name='user',
            new_name='registration_details',
        ),
    ]
