# Generated by Django 5.0.6 on 2024-06-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_user_hostel_room_allotment_registration_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_room_allotment',
            name='hostel_room',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True, verbose_name='hostel_room'),
        ),
    ]
