# Generated by Django 5.0.6 on 2024-06-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_guest_room_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments_for_no_due',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=225, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='no_dues_list',
            name='request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_dues_list', to='api.overall_no_dues_request'),
        ),
        migrations.AlterField(
            model_name='no_dues_list',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=225, verbose_name='status'),
        ),
    ]
