# Generated by Django 5.0.6 on 2024-06-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_departments_for_no_due_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall_no_dues_request',
            name='session',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='no_dues_list',
            name='request_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_dues_list', to='api.overall_no_dues_request'),
        ),
    ]
