# Generated by Django 5.0.6 on 2024-06-08 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_hostel_room_allotment_hostel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_allotment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allotment_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
