# Generated by Django 5.0.6 on 2024-06-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_overall_no_dues_request_session_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments_for_no_due',
            new_name='Departments_for_no_Dues',
        ),
    ]
