# Generated by Django 5.0.6 on 2024-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_departments_for_no_due_departments_for_no_dues'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='registered_date',
            field=models.DateField(blank=True, null=True, verbose_name='registered date'),
        ),
    ]
