# Generated by Django 5.0.6 on 2024-06-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_hostel_allotment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='subject_name'),
        ),
    ]
