# Generated by Django 5.0.6 on 2024-06-22 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_complaint_subject_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_no_due_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hostel_no_due_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
