# Generated by Django 5.0.6 on 2024-06-24 20:13

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_hostel_no_due_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to_profile_pictures),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(11)], verbose_name='registration number'),
        ),
    ]
