# Generated by Django 5.0.6 on 2024-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_personalinformation_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafide',
            name='status',
            field=models.CharField(choices=[('not-applied', 'Not-applied'), ('applied', 'Applied'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=('not-applied', 'Not-applied'), max_length=225, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='hostel_allotment',
            name='status',
            field=models.CharField(blank=True, choices=[('not-applied', 'Not-applied'), ('applied', 'Applied'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not-applied', max_length=225, null=True),
        ),
    ]
