# Generated by Django 5.0.6 on 2024-06-24 19:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_personalinformation_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to_profile_pictures),
        ),
    ]
