# Generated by Django 5.0.6 on 2024-06-25 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_guest_room_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifySemesterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=300, verbose_name='remarks')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=225, verbose_name='status')),
                ('registration_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_details', to='api.semester_registration')),
            ],
        ),
    ]
