# Generated by Django 5.0.6 on 2024-06-29 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_verifysemesterregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinformation',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='course_enrolled',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='course_start_date',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='current_year',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='major',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='program',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='year_semester',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='alternate_phone_number',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='state',
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='board',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('BSEB', 'BSEB'), ('others', 'Others')], max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='category',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='college_name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='college name'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True, verbose_name='date of admission'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='last_qualification',
            field=models.CharField(blank=True, choices=[('matric', 'Matric'), ('intermediate', 'Intermediate'), ('polytechnic', 'Polytechnic')], max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='merit_serial_number',
            field=models.CharField(default=None, max_length=225, null=True, verbose_name='merit serial number'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='registration_year',
            field=models.DateField(blank=True, null=True, verbose_name='registration year'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='school',
            field=models.CharField(default=None, max_length=225, null=True, verbose_name='school'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='session',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='session'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='university_reg_no',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='university registration number'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='year'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='fathers_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='fathers phone number'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='student_email',
            field=models.EmailField(blank=True, max_length=225, null=True, verbose_name='student email address'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='student_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='student phone number'),
        ),
        migrations.AddField(
            model_name='hostel_no_due_request',
            name='status',
            field=models.CharField(choices=[('not-applied', 'Not-applied'), ('applied', 'Applied'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not-applied', max_length=225),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='correspndance_address',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='correspndance address'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='isCorrespndance_same',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='both address same'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='permanent_address',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='permanent address'),
        ),
        migrations.AddField(
            model_name='semester_registration',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=225, null=True),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=400, null=True, verbose_name='message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nofications_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferCertificate_or_CharacterCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC_or_CL_no', models.CharField(blank=True, max_length=225, null=True, verbose_name='TC_or_CL_no')),
                ('issuing_date_tc', models.DateField(blank=True, null=True, verbose_name='issuing_date_tc')),
                ('purpose', models.CharField(blank=True, max_length=225, null=True, verbose_name='purpose')),
                ('character_certificate_issued', models.BooleanField(default=False, verbose_name='character_certificate_issued')),
                ('character_certificate_no', models.CharField(blank=True, max_length=225, null=True, verbose_name='character_certificate_no')),
                ('issuing_date_cr', models.DateField(blank=True, null=True, verbose_name='issuing_date_cr')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TransferCertificate_or_CharacterCertificate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tc_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tc_information', to='api.transfercertificate_or_charactercertificate'),
        ),
    ]
