# Generated by Django 5.0.6 on 2024-06-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_academicinformation_batch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransferCertificate_or_CharacterCertificate',
            new_name='TransferCertificateInformation',
        ),
    ]
